on: workflow_dispatch

name: Manual Push to ECR

jobs:
  deploy:
    name: Push to ECR
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION_NAME }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION_NAME: ${{ secrets.AWS_REGION_NAME }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
        DJANGO_SETTINGS_MODULE: ${{ secrets.DJANGO_SETTINGS_MODULE }}
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        DJANGO_ALLOWED_HOSTS: ${{ secrets.DJANGO_ALLOWED_HOSTS }}
        DJANGO_DEFAULT_FROM_EMAIL: ${{ secrets.DJANGO_DEFAULT_FROM_EMAIL }}
        DJANGO_SWAGGER_ENABLED: ${{ secrets.DJANGO_SWAGGER_ENABLED }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        REDIS_CACHE_URL: ${{ secrets.REDIS_CACHE_URL }}
        CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
        CORS_ALLOWED_ORIGINS: ${{ secrets.CORS_ALLOWED_ORIGINS }}
        DEFAULT_TO_EMAIL: ${{ secrets.DEFAULT_TO_EMAIL }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        AWS_SES_CONFIGURATION_SET: ${{ secrets.AWS_SES_CONFIGURATION_SET }}
      run: |
        mv docker/production/django/Dockerfile.* ./ && rm -rf ./docker/ci && rm -rf ./docker/local
        docker build -t $ECR_REPOSITORY:web -f ./Dockerfile.web --build-arg CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS --build-arg AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_REGION_NAME=$AWS_REGION_NAME --build-arg DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE --build-arg DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY --build-arg DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS --build-arg DJANGO_DEFAULT_FROM_EMAIL=$DJANGO_DEFAULT_FROM_EMAIL --build-arg DJANGO_SWAGGER_ENABLED=$DJANGO_SWAGGER_ENABLED --build-arg DATABASE_URL=$DATABASE_URL --build-arg REDIS_CACHE_URL=$REDIS_CACHE_URL --build-arg CELERY_BROKER_URL=$CELERY_BROKER_URL --build-arg HOST=$HOST --build-arg PORT=$PORT --build-arg MAILGUN_API_KEY=$MAILGUN_API_KEY --build-arg MAILGUN_DOMAIN=$MAILGUN_DOMAIN --build-arg DEFAULT_TO_EMAIL=$DEFAULT_TO_EMAIL --build-arg SENTRY_DSN=$SENTRY_DSN --build-arg AWS_SES_CONFIGURATION_SET=$AWS_SES_CONFIGURATION_SET .
        docker push $ECR_REPOSITORY:web
        docker build -t $ECR_REPOSITORY:worker -f ./Dockerfile.worker --build-arg CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS --build-arg AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_REGION_NAME=$AWS_REGION_NAME --build-arg DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE --build-arg DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY --build-arg DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS --build-arg DJANGO_DEFAULT_FROM_EMAIL=$DJANGO_DEFAULT_FROM_EMAIL --build-arg DJANGO_SWAGGER_ENABLED=$DJANGO_SWAGGER_ENABLED --build-arg DATABASE_URL=$DATABASE_URL --build-arg REDIS_CACHE_URL=$REDIS_CACHE_URL --build-arg CELERY_BROKER_URL=$CELERY_BROKER_URL --build-arg HOST=$HOST --build-arg PORT=$PORT --build-arg MAILGUN_API_KEY=$MAILGUN_API_KEY --build-arg MAILGUN_DOMAIN=$MAILGUN_DOMAIN --build-arg DEFAULT_TO_EMAIL=$DEFAULT_TO_EMAIL --build-arg SENTRY_DSN=$SENTRY_DSN --build-arg AWS_SES_CONFIGURATION_SET=$AWS_SES_CONFIGURATION_SET .
        docker push $ECR_REPOSITORY:worker
        docker build -t $ECR_REPOSITORY:scheduler -f ./Dockerfile.scheduler --build-arg CORS_ALLOWED_ORIGINS=$CORS_ALLOWED_ORIGINS --build-arg AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY --build-arg AWS_REGION_NAME=$AWS_REGION_NAME --build-arg DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE --build-arg DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY --build-arg DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS --build-arg DJANGO_DEFAULT_FROM_EMAIL=$DJANGO_DEFAULT_FROM_EMAIL --build-arg DJANGO_SWAGGER_ENABLED=$DJANGO_SWAGGER_ENABLED --build-arg DATABASE_URL=$DATABASE_URL --build-arg REDIS_CACHE_URL=$REDIS_CACHE_URL --build-arg CELERY_BROKER_URL=$CELERY_BROKER_URL --build-arg HOST=$HOST --build-arg PORT=$PORT --build-arg MAILGUN_API_KEY=$MAILGUN_API_KEY --build-arg MAILGUN_DOMAIN=$MAILGUN_DOMAIN --build-arg DEFAULT_TO_EMAIL=$DEFAULT_TO_EMAIL --build-arg SENTRY_DSN=$SENTRY_DSN --build-arg AWS_SES_CONFIGURATION_SET=$AWS_SES_CONFIGURATION_SET .
        docker push $ECR_REPOSITORY:scheduler
